// Auto-generated by LibreLane
module ALU(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst,
  input i_vld,
  input[31:0] i_a,
  input[31:0] i_b,
  input opcode,
  output[31:0] o_res,
  output o_res_vld,
  output overflow
);
endmodule
